export default {
  TYPE_INPUT: "TYPE_INPUT",
  SET_TOKEN: "SET_TOKEN",
  RESET_INPUTS: "RESET_INPUTS",
  SET_POSTS: "SET_POSTS",
  SET_ERROR: "SET_ERROR",
  SET_BOOL: "SET_BOOL",
  RESET_POSTS: "RESET_POSTS",
};
